"""playlist connect to channel

Revision ID: 62b62aeacdeb
Revises: 25770f265a7c
Create Date: 2021-06-01 08:18:02.916659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b62aeacdeb'
down_revision = '25770f265a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_playlists', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk__youtube_playlists__channel_id__youtube_channels'), 'youtube_playlists', 'youtube_channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__youtube_playlists__channel_id__youtube_channels'), 'youtube_playlists', type_='foreignkey')
    op.drop_column('youtube_playlists', 'channel_id')
    # ### end Alembic commands ###
