"""create youtube channels

Revision ID: c8ac14f4ea7f
Revises: 
Create Date: 2021-05-31 14:52:39.480330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ac14f4ea7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__youtube_channels')),
    sa.UniqueConstraint('url', name=op.f('uq__youtube_channels__url'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_channels')
    # ### end Alembic commands ###
